#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_DIR/scripts/AllwmakeParseArguments

[ -n "$IPM_LIBPATH" ] || {
    echo "Allwmake error: IPM_LIBPATH not set"
    echo "    Set this environment variable to enable proper compilation"
    exit 1
}

[ -n "$ACCELERINT_PATH" ] || {
    echo "Allwmake error: ACCELERINT_PATH not set"
    echo "    Set this environment variable to enable proper compilation"
    exit 1
}

[ -n "$ACCELERINT_LIB_PATH" ] || {
    echo "Allwmake error: ACCELERINT_LIB_PATH not set"
    echo "    Set this environment variable to enable proper compilation"
    exit 1
}

[ -n "$PYJAC_PATH" ] || {
    echo "Allwmake error: PYJAC_PATH not set"
    echo "    Set this environment variable to enable proper compilation"
    exit 1
}

[ -n "$PYJAC_LIB_PATH" ] || {
    echo "Allwmake error: PYJAC_LIB_PATH not set"
    echo "    Set this environment variable to enable proper compilation"
    exit 1
}

[ -n "$WRAPPER_PATH" ] || {
    echo "Allwmake error: WRAPPER_PATH not set"
    echo "    Set this environment variable to enable proper compilation"
    exit 1
}

[ -n "$CL_INC_DIR" ] || {
    echo "Allwmake error: CL_INC_DIR not set"
    echo "    Set this environment variable to enable proper compilation"
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

# Compile supporting libraries
wmake BatchedODE
wmake chemistryModelsIPM
wmake combustionModelsIPM
wmake reactingFoamIPM
wmake chemFoamIPM
wmake testODE

#------------------------------------------------------------------------------
