#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Compile supporting libraries
wclean StandardChemistryModelIPM
wclean combustionModelsIPM
wclean .

#------------------------------------------------------------------------------
