#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# convert mechanism to ct format
python -m cantera.ck2cti --input ../chemkin/chem.inp --thermo ../chemkin/therm.dat \
    --permissive --output chem.cti

# run cantera
python ct_plot.py


./createGraph

#------------------------------------------------------------------------------
