#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# set number of processors
export IPM_NESTED_REGIONS=1
num_proc="10"
foamDictionary -entry "numberOfSubdomains" -set "$num_proc" system/decomposeParDict

# Set application name
application="mpirun -np $num_proc $(getApplication) -parallel"

runApplication chemkinToFoam \
               chemkin/grimech30.dat chemkin/thermo30.dat chemkin/transportProperties \
               constant/reactionsGRI constant/thermo.compressibleGasGRI

runApplication ck2cti \
               --input=chemkin/grimech30.dat \
               --thermo=chemkin/thermo30.dat \
               --output=chemin/grimech30.cti \
               --permissive

runApplication blockMesh
runApplication setFields
runApplication decomposePar -latestTime

# Run the application without chemistry until 1500 to let the flow field develop
foamDictionary -entry "startTime" -set "0" system/controlDict
foamDictionary -entry "writeInterval" -set "1500" system/controlDict
foamDictionary -entry "endTime" -set "1500" system/controlDict
foamDictionary -entry "chemistry" -set "off" constant/chemistryProperties
foamDictionary -entry "deltaT" -set "1" system/controlDict
foamDictionary -entry "ddtSchemes.default" -set "localEuler" system/fvSchemes

runApplication $application

# Run with chemistry until flame reach its full size
foamDictionary -entry "startTime" -set "1500" system/controlDict
foamDictionary -entry "writeInterval" -set "100" system/controlDict
foamDictionary -entry "endTime" -set "5000" system/controlDict
foamDictionary -entry "chemistry" -set "on" constant/chemistryProperties
foamDictionary -entry "Treact" -remove constant/chemistryProperties

runApplication -o $application

# finally, run in a non-LTS mode for 5 ms to get a time-dependent validation
foamDictionary -entry "startTime" -set "5000" system/controlDict
foamDictionary -entry "writeInterval" -set "1e-3" system/controlDict
foamDictionary -entry "endTime" -set "5000.01" system/controlDict
foamDictionary -entry "ddtSchemes.default" -set "backward" system/fvSchemes
foamDictionary -entry "deltaT" -set "1e-6" system/controlDict
foamDictionary -entry "Treact" -set "500" constant/chemistryProperties

runApplication -o $application

#------------------------------------------------------------------------------
